### ISSUE TITLE
Some blocks missing

### ISSUE THREAD

**Issue by pintail-xyz** [wealdtech/chaind#1]
When running back through the parent roots, occasional blocks are found to be missing from the database. The missing blocks are available from the beacon node, and when forced to retrieve them individually they can be added to the `t_blocks` table. Possibly these blocks were not available when chaind was originally running (due to high network stress?).

Suggest an option for retrying all empty slots to pick up any missing blocks.

**Comment by mcdee** [comment]
chaind 0.2.0 now fetches any missing canonical blocks as part of its finalization process.
