### ISSUE TITLE
ChainD stopped synching after Dencun

### ISSUE THREAD

**Issue by got3nks** [wealdtech/chaind#103]
After the Dencun fork, ChainD stopped synching.

`{"level":"error","service":"blocks","impl":"standard","slot":8626176,"error":"failed to update block: failed to obtain beacon block for slot: failed to parse response: unrecognised data version \"deneb\"","time":"2024-03-13T15:23:48+01:00","message":"Failed to catchup"}`

**Comment by mcdee** [comment]
Which version of chaind is this?
