### ISSUE TITLE
Using int instead of bigint in big postgres tables

### ISSUE THREAD

**Issue by henridf** [wealdtech/chaind#29]
My postgres DB  is using a lot of space (~1.5TB) and I noticed that many rows use postgres `bigint` where `int` would suffice.  For example, in the validator balances table (about 500GB): 

```
chain=> \d t_validator_balances 
              Table "public.t_validator_balances"
       Column        |  Type  | Collation | Nullable | Default 
---------------------+--------+-----------+----------+---------
 f_validator_index   | bigint |           | not null | 
 f_epoch             | bigint |           | not null | 
 f_balance           | bigint |           | not null | 
 f_effective_balance | bigint |           | not null | 
```

only f_balance needs to be a bigint (8 bytes), and the others could be int (4 bytes). This should reduce the size of the table considerably, since rows would go from 32 to 20 bytes. 

Would you be open to a PR changing this?  I think the change itself to chaind would be relatively small/straightforward, probably the migration (if needed?) would be more work.

**Comment by mcdee** [comment]
There are a couple of things here.  

On a theoretical level, the Ethereum spec states that these values are all `uint64` hence the use of `bigint` (which even then isn't perfect, as we're missing one bit, but it's at least the correct size and simple translations of things like `0xffffffffffffffff`work).

On a practical level, changing the types wouldn't give the easiest upgrade path.  And realistically we could trim around 8 bytes off the table if we did this (`f_effective_balance` needs to remain a `bigint`) so not sure how much of a benefit it would bring.

If you want to give it a try to see the impact, feel free to do so and report back here.

**Comment by henridf** [comment]
> f_effective_balance needs to remain a bigint

Your article [here](https://www.attestant.io/posts/understanding-validator-effective-balance/)  says "Effective balance is always a multiple of 1Ξ", and anectodally I verified this was the case in the postgres table.  Am I missing something as to why it needs to remain a bigint?

**Comment by henridf** [comment]
On reflecting further, I realize this kind of tactical fix is more work than it's worth, and just a stopgap. This time would probably be better spent adding support for a columnar store such as clickhouse. Thanks for your input @mcdee !
