### ISSUE TITLE
Slow catchup

### ISSUE THREAD

**Issue by henridf** [wealdtech/chaind#30]
Opening this issue to document/discuss a setup where it's taking a long time for chaind to catchup.

### Setup 

**Server**
This is all running on a beefy server (AMD's Ryzen 9 3900 CPU, 12 core, 128GB RAM). I'm running teku, chaind, and postgres on the server. (This is my test/dev env, production will run in a cloud in a different config).

Though all of this, the server seems to have ample memory capacity. CPUs are mostly idle, but I do see some spikes on a single core at times, presumably either teku or chaind have some single-threaded bottlenecks (but I haven't dug in). Storage i/o does not appear to be saturated.

**Teku**
```
$ ./bin/teku --version
teku/v21.9.2/linux-x86_64/-ubuntu-openjdk64bitservervm-java-11

./bin/teku --rest-api-enabled --data-storage-mode=archive --rest-api-interface=0.0.0.0 --rest-api-host-allowlist=*
...
```

**Chaind**
- running commit 88d4a5a10da170e9e704be0ee7e78e689103a416 (which was HEAD when I first installed)
- running with everything enabled: `./chaind --chaindb.url=postgres://chain:cha1n@localhost:5432 --eth2client.address=localhost:5051 --eth1client.address=xyz  --validators.balances.enable=true --summarizer.validators.enable=true`

### Observations

```
chain=> select * from t_metadata ;
           f_key           |                                        f_value                                        
---------------------------+---------------------------------------------------------------------------------------
 schema                    | {"version": 4}
 summarizer.standard       | {"latest_epoch": 35966, "latest_block_epoch": 35966, "latest_validator_epoch": 35710}
 proposerduties.standard   | {"latest_epoch": 71817}
 beaconcommittees.standard | {"latest_epoch": 71817}
 finalizer.standard        | {"latest_epoch": 71814, "latest_canonical_slot": 2298112}
 blocks.standard           | {"latest_slot": 2298170}
 validators.standard       | {"latest_epoch": 71814, "latest_balances_epoch": 36014}
(7 rows)
```

This is where I'm at after several days running chaind. Everything is caught up except for validator balances and summarizer. 

My understanding of the chaind fetching/processing dependencies is that validator balances is the bottleneck, given that the epoch summarizer can't process epochs without validator balances, and the block/validator summarizers are themselves gated on the epoch summarizer.

I dug in and from the logs and also prom metrics, it looks like the validator service is taking order of 10 seconds per epoch. (Informally, I also noticed that this number grows as we advance in the epochs...).

I've played around with `curl`-ing the resources that chaind fetches from the beacon node to populate the validator balances (`eth/v1/beacon/states/35967/validators`) and have seen it take anywhere from 0.5s to 5-7s for the responses to come back. (These  are pretty big json blobs, ~15MB). Haven't dug in enough to understand the variance.

### Thoughts / open questions

This is a snapshot of what I've collected so far.  Maybe there's some teku config/flag I missed that could make it respond faster to the validators requests. Maybe some or all of the above is ill-informed or doesn't make sense :) 

In any case, I'll be happy to provide more info if useful, and look forward to hearing any thoughts or suggestions !

**Comment by henridf** [comment]
The version i'm running already includes #23  🙂 

Elsewhere I got a recommendation to use the `--data-storage-archive-frequency` teku param to set something lower than the default 2048. I'll try that.

**Comment by henridf** [comment]
Shouldn't the readme have the same recommendations for the flag for teku then? I can put up a PR if so.

**Comment by mcdee** [comment]
Not necessarily.  There is a time/space trade-off for each of the products that is different due to their differing architectures.  You could try some values and report back on a recommended value to use, but copying the value from another product is unlikely to yield optimal results.

**Comment by henridf** [comment]
Ok. My experience is that the recommended (default) setting on teku is not working well for chaind. I'd be curious, which setting do you use and (very roughly how long does it take for chaind to catch up validator balances with that setting?

**Comment by henridf** [comment]
Thanks @mcdee. 

Closing this issue. 

For anyone who comes along, the tldr is that syncing validator balances is the bottleneck for summarizers, and when that is all enabled, it takes a long time to catch up, and one avenue to speeding that up is by reducing the archive snapshot interval on the beacon node. Which of course means more archive storage and (at least in the case of teku) re-syncing from scratch. I'm doing that right now (with `--data-storage-archive-frequency 32`) and will see if / how much it helps chaind.
