### ISSUE TITLE
Can't restart chaind. Duplicated tables error

### ISSUE THREAD

**Issue by alrevuelta** [wealdtech/chaind#37]
I have `chaind` up and running working perfectly, but if I need to restart it, it fails due to duplicated tables. It can be fixed by emptying the database, but this implies losing everything.

```console
{"level":"error","error":"failed to upgrade chain database: failed to upgrade: failed to add f_parent_distance to block epoch summaries table: ERROR: column \"f_parent_distance\" of relation \"t_block_summaries\" already exists (SQLSTATE 42701)","time":"2021-12-07T12:57:14Z","message":"Failed to initialise services"}
```

Thanks!

**Comment by mcdee** [comment]
Please could you share the output of `SELECT * FROM t_metadata;` in the database?

**Comment by alrevuelta** [comment]
> Please could you share the output of SELECT * FROM t_metadata; in the database?

"schema"	"{""version"": 3}"
"synccommittees.standard"	"{""latest_period"": 292}"
"blocks.standard"	"{""latest_slot"": 0}"

**Comment by mcdee** [comment]
Thank you, this is a bug when upgrading the database.  To fix this in your installation please stop chaind, run

```
ALTER TABLE t_block_summaries DROP COLUMN f_parent_distance;
```

against your database, then restart chaind.  The log file should report that the database is upgrading ,and when it states that the upgrade is complete a query of the `t_metadata` table as per the earlier comment should show a schema version of `5`.  Please let me know if this succeeds.

Note that this has been addressed permanently in 97df14ad6a950ae2f07214266678422121022f78  and will be available in a future release.

**Comment by alrevuelta** [comment]
Perfect thanks! Also tested 97df14a and works perfectly. Feel free to close now or when released.

**Comment by mcdee** [comment]
Thanks for the update.
