### ISSUE TITLE
After few hours, chaind gets stuck

### ISSUE THREAD

**Issue by alrevuelta** [wealdtech/chaind#39]
After having `chaind` running ok for few hours it gets stuck:
* The cpu consumption goes to zero and stops synching.
* No logs are produced in `debug` mode anymore.
* `t_metadata` shows that there are some tables still not in sync.
* I managed to reproduce this issue multiple times, it usually happens after 8 hours.

Restarting it fixes the issue, but perhaps there is deadlocking situation not so difficult to fix. I tried running a pprof with `--profile-address` but I'm not versed in profilers, so not sure where to look into. Wouldn't mind helping to debug and fix the issue with some assistance.

Thanks!

**Comment by mcdee** [comment]
Which version of `chaind` is this with, and how is it run?  Also, which  beacon node is this using, and what are the beacon node parameters?

Most of `chaind` data gathering is triggered from receiving `head` events from the beacon node, so that would be a good place to start.  In your `chaind.yml` file please can you set the following:

```
eth2client:
  log-level: trace
blocks:
  log-level: trace
```

Note this will generate a lot of log entries, but we're only really interested in what happens once `chaind` gets stuck.  When it stops processing see if there are any log entries produced.

**Comment by alrevuelta** [comment]
* `chaind` version: 97df14a
* `chaind` parameters, quite vanilla setup:
  * --eth1deposits.enable=true
  * --chaindb.url=xxx
  * --eth2client.address=xxx
  * --log-level=debug
  * --eth1client.address=xxx
* `beacon-node`:
  * teku v21.12.1
  * --data-storage-mode=archive
  * --data-storage-archive-frequency=64
  * fully synched and plenty of cpu/memory allocated.

As discussed with other `chaind` users, other people are reporting the same issue. Not sure about the version or configuration they are using though.

Will enable those flags and let you know. Thanks for the help.

**Comment by mcdee** [comment]
Has this problem shown up again?

**Comment by ariskk** [comment]
It occurs ~weekly I would say and gets resolved with a restart. This behaviour has been consistent across all the recent versions (including `0.5.4`). Our setup is using chaind with Lighthouse. My guess would be a rare race condition that leads to a deadlock either in PG or chaind itself. I have a ticket to check Postgres for clues next time this occurs.

**Comment by alrevuelta** [comment]
Yes, in my case I would say it was every 2-3 days with the configuration above. As you say, restarting solves the issue. I ended up setting a liveness probe to fail every day or so that it was automatically restarted. Tried debugging the issue with a profiler but didn't get very far.

**Comment by mcdee** [comment]
Have there been any more hangs?  I have been running chaind with lighthouse for the past 4 weeks and not seen any here.

**Comment by alrevuelta** [comment]
I'm not running it, can't tell.

**Comment by ariskk** [comment]
I haven't seen a dead hang in a couple of weeks. What does happen though sometimes is `t_validators` isn't updated, which is likely due the chain head listener not picking up new events.  I have the profiler on and will investigate when it happens again.

**Comment by ariskk** [comment]
We may be able to close this one soon. We have tracked down this issue to some queries being occasionally blocked in Postgres (which leads to a deadlock). @mcdee has submitted a fix for this https://github.com/wealdtech/chaind/commit/36338be9de64f59a436459404a1700c6a86e4ece  
We will need a few days to confirm but so far it looks good.

**Comment by ariskk** [comment]
We haven't detected this problem since the last round of fixes was released.

**Comment by mcdee** [comment]
Great to hear, I'll close this now and if you see it happen again feel free to reopen.
