### ISSUE TITLE
Feature Request: Store Logs in t_eth1_deposits

### ISSUE THREAD

**Issue by alrevuelta** [wealdtech/chaind#44]
## Feature request
Store more information in the `t_eth1_deposits`, so that when smart contract(s) are involved in the deposit transaction, their addresses are part of the table so that they can be used as filtering criteria. For example, a deposit transaction initiated by an EOA `address_1` but whose funds are held by a smart contract `address_2` will have as `t_eth1_deposits. f_eth1_sender` field `address_1` but `address_2` won't be stored anywhere: Few examples:

* [1] https://etherscan.io/tx/0x09dcdf1a9b2872d18651f830e4e0a433bfe8a9c2d00be8cb8a7c3fcbbcdd1529
* [2] https://etherscan.io/tx/0xaa686f8cad8e31d71fefa7872694cbd22700d320ea393e7914a9ff896435fa98

Since many pools are doing their deposits through smart contracts, and the transactions are initiated by hundreds of different EOAccounts, this feature will come in handy when querying the validators that belong to any of these pools.

Luckily, the information is already in the tx receipt `transactionReceipt.Logs.Address`, with one entry "per hop". So the only thing that would be required is parsing this information and storing it in a new column of `t_eth1_deposits`.

## Proposed implementation

Before starting implementing this feature, would like to i) know if it's relevant for the repo and ii) discuss possible technical solutions.

Some alternatives:
* Add a new column in `t_eth1_deposits` named `f_path`, storing the smart contracts involved in the deposit. In most cases, it will be just one [2] but in other cases, more than one contract is involved [1]. This information can be retrieved from `transactionReceipt.Logs[].Address` and we just need to filter the deposit contract and the sender itself. Then one can query from example the validators that were deposited from/interacting with a given smart contract, i.e. Lido.
* Another way could be to add to `t_eth1_deposits` a field named `f_payer` that stores the actual address that paid for the deposit. In normal cases `f_payer=f_eth1_sender ` but in the cases that the EOA (aka `f_eth1_sender`) is not the one sending the eth, the smart contract sending it will be stored instead. Perhaps this won't fully implement the requested feature, but will at least store the actual payer of the eth that was used for the deposit.

Perhaps interesting for Rated?
@ariskk

**Comment by ariskk** [comment]
A version of this (the `f_path` alternative, implemented as an array in PG) would be indeed quite useful.
I would argue this isn't outside of chaind's scope.

**Comment by mcdee** [comment]
If I understand this correctly then for the vast majority of cases the `f_recipient` field in `t_eth1_deposits` should suffice, as that is the address to which the transaction is sent (in the above cases it will be the smart contract).

In the situation where one smart contract calls another this information would not be available directly.  We could attempt to obtain this information from logs, but there are various places where it would fail.  Is the presence of `f_recipient` enough to address the requirement, and if not please could you expand on the use case where more information is required?

**Comment by alrevuelta** [comment]
> If I understand this correctly then for the vast majority of cases the f_recipient field in t_eth1_deposits should suffice, as that is the address to which the transaction is sent (in the above cases it will be the smart contract).

As you are saying `f_receipient` is not enough, since it will always store the eth2 deposit smart contract. What I'm trying to get is where the Eth actually comes from, not where it ends. Note that the Eth does not always come from `f_eth1_sender`.

> In the situation where one smart contract calls another this information would not be available directly.

I ran a quick test and I believe all this information is available in `transactionReceipt.Logs[].Address`.

> but there are various places where it would fail

Can you elaborate where it could fail?

> could you expand on the use case where more information is required?

I can try to elaborate more, but let me know if there is something from the issue description that is not clear.

So currently we are storing `f_eth1_sender`, and this points to the EOA account that started the deposit transaction. The thing is that this address is not really the "eth1 sender". The 32 Eth can come from a smart contract, and `f_eth1_sender` is just the address that triggers it but doesn't actually send the Eth. It's also common to see even two smart contracts involved in the deposit EOA->SmartContract1->SmartContract2->Eth2DepositContract. What I would like is to also store this information.

The main use case is to be able to query the deposits made by a given smart contract (i.e. [stakewise](https://etherscan.io/address/0xc874b064f465bdd6411d45734b56fac750cda29a). With the current information stored in `t_eth1_deposits` that's not possible, unless you know all the EOA that interacted with that smart contract, and that's not trivial. Same applies to Lido (see tx above).

**Comment by mcdee** [comment]
> As you are saying `f_receipient` is not enough, since it will always store the eth2 deposit smart contract.

The field stores the address to which the transaction was sent, not from where the events originated.  In the case of the first transaction provided above:

```
SELECT * FROM t_eth1_deposits WHERE f_eth1_tx_hash = '\x09dcdf1a9b2872d18651f830e4e0a433bfe8a9c2d00be8cb8a7c3fcbbcdd1529';
-[ RECORD 1 ]------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
f_eth1_block_number      | 14774089
f_eth1_block_hash        | \xd9291fd04313e13859b298d759ef32e6dbf97fa961ed236d7cb12014c6f31c78
f_eth1_block_timestamp   | 2022-05-14 14:24:34+00
f_eth1_tx_hash           | \x09dcdf1a9b2872d18651f830e4e0a433bfe8a9c2d00be8cb8a7c3fcbbcdd1529
f_eth1_log_index         | 238
f_eth1_sender            | \xad4eb63b9a2f1a4d241c92e2bba78eefc56ab990
f_eth1_recipient         | \x8a887282e67ff41d36c0b7537eab035291461acd
f_eth1_gas_used          | 317590
f_eth1_gas_price         | 55178497385
f_deposit_index          | 398683
f_validator_pubkey       | \xac2c6774fe8b3dc2cd42eb5f319f40e5de4f47c9c37ba79bd2971faf6b19853d22aa7f7711dbb37c33dc996b2d129548
f_withdrawal_credentials | \x0100000000000000000000002296e122c1a20fca3cac3371357bdad3be0df079
f_signature              | \xb1d1600f5ee89eba8d5b32337749f1b47cc01c7db78f2780b10eedc642ebd865884bb5bc363aa2a0645c866b7aebf4b905dcb3bbd1061b4c407ed3115de98c838ad7ce0b3cfb3c8eaff611a2313f91245b214a843b47ecefb93258769abb59e7
f_amount                 | 32000000000
```

and `f_eth1_recipient` contains the address of the Stakewise smart contract.  As such, if you wanted to know for example how many deposits were triggered by that contract then:

```
$ SELECT COUNT(*) FROM t_eth1_deposits WHERE f_eth1_recipient = '\x8a887282e67ff41d36c0b7537eab035291461acd';
-[ RECORD 1 ]
count | 976
```

> I ran a quick test and I believe all this information is available in `transactionReceipt.Logs[].Address`.

This only contains information about events that were emitted, and has no information about their ordering or details about contracts that did not emit events.  If, for example, smart contract A called smart contract B that then called the Ethereum deposit contract, but smart contract B did not emit any event, there would be no information about it in the logs.  Alternatively, if smart contract A called smart contract B, which then returned to smart contract A and smart contract A then called the Ethereum deposit contract then a simple path output could show `A->B->deposit` when this was not the path followed.

Taking a look at the Lido example it seems that the same process can be applied, although you may be better off taking the validator public keys direct from the Lido smart contract.

**Comment by alrevuelta** [comment]
Thanks for the info @mcdee ! Much appreciated. I was wrong about `f_eth1_recipient`. The feature that I was requesting is kind of already there, so closing :)
