### ISSUE TITLE
validator epoch summaries slow insert

### ISSUE THREAD

**Issue by henridf** [wealdtech/chaind#54]
Now that I have epoch summaries running fast, the next bottleneck is the validator epoch summaries (taking a few minutes per epoch).

Here's some timing info:

```
{"level":"debug","service":"summarizer","impl":"standard","epoch":113760,"time":"2022-06-28T09:46:28Z","message":"Summarizing validator epoch"}
{"level":"debug","service":"summarizer","impl":"standard","epoch":113760,"elapsed":3.292788,"time":"2022-06-28T09:46:28Z","message":"Fetched proposer duties"}
{"level":"debug","service":"summarizer","impl":"standard","epoch":113760,"elapsed":6.130568,"time":"2022-06-28T09:46:28Z","message":"Fetched proposals"}
{"level":"debug","service":"summarizer","impl":"standard","attestations":3533,"epoch":113760,"time":"2022-06-28T09:46:29Z","message":"Fetched attestations"}
{"level":"debug","service":"summarizer","impl":"standard","epoch":113760,"elapsed":2808.496565,"time":"2022-06-28T09:46:31Z","message":"Fetched attestations"}
{"level":"debug","service":"summarizer","impl":"standard","epoch":113760,"elapsed":234669.602992,"time":"2022-06-28T09:50:23Z","message":"Set summary"}
```

I'd be happy to make a change but I'm not seeing an obvious way to speed the insert; any thoughts?

**Comment by henridf** [comment]
No surprise I think: it's the db insert that's taking up all this time.

```
{"level":"debug","service":"summarizer","impl":"standard","epoch":114357,"time":"2022-06-30T17:40:31Z","message":"Summarizing validator epoch"}
{"level":"debug","service":"summarizer","impl":"standard","epoch":114357,"elapsed":14.041798,"time":"2022-06-30T17:40:31Z","message":"Fetched proposer duties"}
{"level":"debug","service":"summarizer","impl":"standard","epoch":114357,"elapsed":21.301003,"time":"2022-06-30T17:40:31Z","message":"Fetched proposals"}
{"level":"debug","service":"summarizer","impl":"standard","attestations":3603,"epoch":114357,"time":"2022-06-30T17:40:31Z","message":"Fetched attestations"}
{"level":"debug","service":"summarizer","impl":"standard","epoch":114357,"elapsed":4024.621654,"time":"2022-06-30T17:40:35Z","message":"Fetched attestations"}
# new log below with message "Compute summary"
{"level":"debug","service":"summarizer","impl":"standard","epoch":114357,"elapsed":4404.422445,"time":"2022-06-30T17:40:35Z","message":"Compute summary"} 
{"level":"debug","service":"summarizer","impl":"standard","epoch":114357,"elapsed":434532.276416,"time":"2022-06-30T17:47:45Z","message":"Set summary"}
``

**Comment by mcdee** [comment]
If it is the insert itself then there isn't a lot we can do in the code.  We are already using the PGX copy system, which should speed things up significantly compared to individual inserts.

Regarding speeding up the database, there are a few things that you could try:
  - optimise your disks.  Using higher speed SSDs (NVMe-based) can help, as can using more disks.  Tweaking your mount options can also help
  - optimise your postgresql configuration.  There is a lot you can do here, especially if you have a lot of memory on your server
  - make sure there aren't any read large read queries running against the database when you are attempting to update the data

Just checked the latest logs from one of our servers on mainnet and have the following:

```
{"level":"trace","service":"summarizer","impl":"standard","epoch":129674,"elapsed":1540.533487,"time":"2022-06-30T20:13:27Z","message":"Fetched attestations"}
{"level":"trace","service":"summarizer","impl":"standard","epoch":129674,"elapsed":15625.305903,"time":"2022-06-30T20:13:41Z","message":"Set summary"}
```

That's 15.5 seconds for the entire summary process, and 14 seconds for carrying out the inserts, so there should be some room to bring this in a bit with sufficient tweaking of your configuration and/or hardware.

**Comment by henridf** [comment]
Thanks, it's good to hear that you're getting 14 second inserts. I'm using a cloud sql instance and will dig in further. I'll report back when I've figure it for anyone curious.

**Comment by henridf** [comment]
And... bumping up the instance size did the trick, now at ~15 second inserts for the above.
Given the speedup, I would guess that something was previously  memory-bound and thrashing around. Unfortunately the monitoring tools were misleading as they always showed no memory pressure. Ah well, problem solved!
