### ISSUE TITLE
failed to connect to database

### ISSUE THREAD

**Issue by SpringBoom** [wealdtech/chaind#58]
I create a user and database in my PostgreSQL. But I can't start chaind in docker, it's eror log: 'failed to start chain database service: failed to connect to database: failed to connect to `host=localhost user=chain database=`: dial error (dial tcp [::1]:5432: connect: cannot assign requested address)'

**Comment by mcdee** [comment]
You could try changing you host to `127.0.0.1`.  Alternatively, your postgresql server may not be configured to listen on port 5432.  You can check that by running `psql -h localhost -U chain` on a command line: if it fails to connect you will need to look at your postgresql configuration to enable it to listen on that port.
