### ISSUE TITLE
How to run?

### ISSUE THREAD

**Issue by karlpascal** [wealdtech/chaind#64]
Probably a stupid question but how do we run this? New to Go but want to test this out for getting consensus/beacon node data. I've installed `chainid`  and set up the configuration as suggested in the README (postgres db and ETH2 client). What am I supposed to do next?

**Comment by mcdee** [comment]
@got3nks you may also want to set `sync-committees.start-period` if you are starting from a different point.  But I tested it just now locally and it works (although note that some items like proposer duties do not have a `start-*` feature so they will sync from genesis).

**Comment by mcdee** [comment]
The period is the sync committee period.  One period is 256 epochs.

You can delete old data, once it has been finalized and summarized (if running the summarizer).
