### ISSUE TITLE
How to run `chaind` with config file, `.chaind.yml` ? 

### ISSUE THREAD

**Issue by sivathanuk** [wealdtech/chaind#65]
I synced the beacon node and trying to run `chaind` with the configuration file `.chaind.yml`.  But, not sure if the synchronization to database is happening. 

## Two key questions:
1. How to ensure that the beacon chain node to database synchronization is happening? 
2. What is the correct approach / command to run the `chaind` executable file with `.chaind.yml` (config_file)?

Your help is much appreciated. 

---
### Working Directory:
 I saved the `.chaind.yml` file in `~/go/bin` location. 

Screenshot of terminal with the  working directory and it's contents:
<img width="523" alt="image" src="https://user-images.githubusercontent.com/62845445/199091974-0f9f72f0-01e7-484f-a5fb-333d651e77dc.png">

#### chaind filetype: 
```shell 
file  chaind
```
output: `chaind: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, Go BuildID=F1TFWIPSGOXeS62j8kfM/LhrJ_g27SVEze1omLb20/5FzRsob3Un2m06IC4uh4/PTQW4Jnak12844ShJ2p0, not stripped`

### Ran `chaind` executable using the below command (working directory:`~/go/bin`)

```shell
./chaind --chaindb.url=postgres://chain:password@localhost:5432/db_name --eth2client.address=localhost:5051
```
output:
`{"level":"info","version":"0.6.15","time":"2022-10-31T19:21:34Z","message":"Starting chaind"}`

and didn't get any further updates after getting the above output. 

---
### Querying the database:
Tried to check the sync updates by querying the table `t_metadata`. But, the query 
```
select * from t_metadata;
``` 
gave the below output:
```shell
 f_key  |    f_value     
--------+----------------
 schema | {"version": 8}
(1 row)
```
 
The query ,
```
select * from t_blocks limit 10;
```
 also returned empty rows as output: 

```shell
f_slot | f_proposer_index | f_root | f_graffiti | f_randao_reveal | f_body_root | f_parent_root | f_state_root | f_canonical | f_eth1_block_hash | f_eth1_deposit_count | f_eth1_deposit_root 
--------+------------------+--------+------------+-----------------+-------------+---------------+--------------+-------------+-------------------+----------------------+---------------------
(0 rows)
```

---

**Comment by mcdee** [comment]
As per the documentation, the `.chaind.yml` file should be in the user's home directory.  If you are running this as `root` then it should be in the `/root` directory.

If you want to see more information you can add `--log-level=trace` to the command and it will tell you exactly what it is trying to do as it does it.  That should tell you what is going on.

**Comment by sivathanuk** [comment]
Thanks a lot. Appreciate the quick response. 

Just confirming the steps and the command syntax once, 

- save the `.chaind.yml` file in the user's home directory  (or `/root` if running as a root) 
- set the working directory  to `~/go/bin`
- and run the below command ? 
`./chaind --chaindb.url=postgres://chain:password@localhost:5432/db_name --eth2client.address=localhost:5051 --log-level=trace`

**Comment by mcdee** [comment]
Note that all of the parameters you have on your command line can be put in your `.chaind.yml` file, but yes the procedure above should be enough to start chaind.

**Comment by sivathanuk** [comment]
Got it, thanks. I added all the parameters on the command line in the `.chaind.yml` file and just ran the `./chaind` ? (typed name of the binary file with no parameters and hit enter)  but didn't get any output or error message. Hence the confusion.

**Comment by sivathanuk** [comment]
Update: Thanks a lot. I am able to run `chaind` after changing the `--eth2client.address=` value from `localhost:5051` to `http://localhost:5051`  (added`http://`)

But I'm not sure if I'm pushing the eth2 client data to chain database in a correct manner. Can you please help and guide me if I'm following the right steps?  I have added more information below,

### More details and context:

I'm running besu + teku, the teku node is synced to the most recent block. Here is the info from  besu and teku sync, 

#### info from Besu tab:
```shell
2022-11-03 04:15:24.670+00:00 | vert.x-worker-thread-0 | INFO  | EngineForkchoiceUpdated | SYNCING for fork-choice-update: head: 0xdd49f2dccbcc18c19b426ae7e5090769a313640d34df4e33b41ab20a0d6b7097, finalized: 0xb09894c16625a397fd0d887e5ff46cf60e452bea648189d4dc09d2a88993e64c, safeBlockHash: 0xfa77e379ba019904b6d4ae1051c3fc23d34f088b117a53dc1a590d7cb8da8077

2022-11-03 04:15:36.641+00:00 | EthScheduler-Services-3 (batchPersistAccountData) | INFO  | SnapsyncMetricsManager | Worldstate download in progress synced=0.18%, accounts=341445, slots=2144679, codes=45686, nodes=2096948
```

#### info from Teku tab:
```shell
04:12:59.502 INFO  - Epoch Event *** Epoch: 157877, Justified checkpoint: 157875, Finalized checkpoint: 157874, Finalized root: 6c977391375165a8d0d08efd4683488f8d5fe95e734dd347d20bd2a54e9a44c9
04:13:11.058 INFO  - Syncing     *** Target slot: 5052064, Head slot: 5052063, Waiting for execution layer sync, Connected peers: 14
04:13:23.082 INFO  - Syncing     *** Target slot: 5052065, Head slot: 5052064, Waiting for execution layer sync, Connected peers: 17
04:13:35.044 INFO  - Syncing     *** Target slot: 5052066, Head slot: 5052065, Waiting for execution layer sync, Connected peers: 18
```
#### info from chaind:
I ran chaind with `--log-level=trace` and here is the information I got,

```shell
{"level":"trace","service":"client","impl":"http","id":"622ee99f","address":"http://localhost:5051","endpoint":"/eth/v1/node/syncing","time":"2022-11-03T04:18:14Z","message":"GET request"}

{"level":"trace","service":"client","impl":"http","id":"622ee99f","address":"http://localhost:5051","response":"{\"data\":{\"head_slot\":\"5052089\",\"sync_distance\":\"0\",\"is_syncing\":true,\"is_optimistic\":true}}","time":"2022-11-03T04:18:14Z","message":"GET response"}

{"level":"debug","time":"2022-11-03T04:18:14Z","message":"Node syncing; will re-test in 1 minute"}

```

But, 
1. teku sync is up to date*
2. But in chaind info, I continue to get  `"message":"Node syncing; will re-test in 1 minute`

---
 #### Querying chain db:
queried the chain database to fetch tables, 
```shell
chain-# \dt
```

output:
```table
 public | t_attestations              | table | chain
 public | t_attester_slashings        | table | chain
 public | t_beacon_committees         | table | chain
 public | t_block_execution_payloads  | table | chain
 public | t_block_summaries           | table | chain
 public | t_blocks                    | table | chain
 public | t_chain_spec                | table | chain
 public | t_deposits                  | table | chain
 public | t_epoch_summaries           | table | chain
 public | t_eth1_deposits             | table | chain
 public | t_fork_schedule             | table | chain
 public | t_genesis                   | table | chain
 public | t_metadata                  | table | chain
 public | t_proposer_duties           | table | chain
 public | t_proposer_slashings        | table | chain
 public | t_sync_aggregates           | table | chain
 public | t_sync_committees           | table | chain
 public | t_validator_balances        | table | chain
 public | t_validator_epoch_summaries | table | chain
 public | t_validators                | table | chain
 public | t_voluntary_exits           | table | chain
```

queried the t_metadata table,
```sql
chain=# select * from t_metadata;
```
output:
```shell
 schema | {"version": 8}
```
---
#### Concern: 
Not very sure if the push from eth2 client to chain database is happening. Also, guess it could be because the teku sync lags by 1 slot 

```shell
04:13:11.058 INFO  - Syncing     *** Target slot: 5052064, Head slot: 5052063, Waiting for execution layer sync, Connected peers: 14
```
and chaind info (with `--log-level=trace` ) displays the below message,
```shell
"message":"Node syncing; will re-test in 1 minute
```
Your help and guidance is much appreciated.

**Comment by mcdee** [comment]
You are waiting for your besu instance to sync before teku is ready to declare itself actually synced.  It cannot know that it is fully synced until besu confirms the blocks are valid.

**Comment by sivathanuk** [comment]
Thanks for the reply. Got it, I too thought in similar lines. Any suggestions on how to fix this so that Chaind can push beacon chain data to the Postgres database ? 

This is the info I keep getting in the chaind tab,

```shell
{"level":"trace","service":"client","impl":"http","id":"1259fa47","address":"http://localhost:5051","endpoint":"/eth/v1/node/syncing","time":"2022-11-04T14:29:15Z","message":"GET request"}

{"level":"trace","service":"client","impl":"http","id":"1259fa47","address":"http://localhost:5051","response":"{\"data\":{\"head_slot\":\"5061983\",\"sync_distance\":\"257\",\"is_syncing\":true,\"is_optimistic\":true}}","time":"2022-11-04T14:29:15Z","message":"GET response"}

{"level":"debug","time":"2022-11-04T14:29:15Z","message":"Node syncing; will re-test in 1 minute"}

{"level":"trace","service":"client","impl":"http","id":"68fd24f0","address":"http://localhost:5051","endpoint":"/eth/v1/node/syncing","time":"2022-11-04T14:30:15Z","message":"GET request"}

{"level":"trace","service":"client","impl":"http","id":"68fd24f0","address":"http://localhost:5051","response":"{\"data\":{\"head_slot\":\"5061983\",\"sync_distance\":\"289\",\"is_syncing\":true,\"is_optimistic\":true}}","time":"2022-11-04T14:30:15Z","message":"GET response"}

{"level":"debug","time":"2022-11-04T14:30:15Z","message":"Node syncing; will re-test in 1 minute"}
```

**Comment by mcdee** [comment]
As I say, the beacon node is not synced because it requires the execution node to also be synced.  Once both nodes are synced the beacon node will state it is no longer syncing and `chaind` can start to gather information.

**Comment by sivathanuk** [comment]
Got it. Just checked the Best sync status, 

```shell
root@ether-client:~# curl -X POST --data '{"jsonrpc":"2.0","method":"eth_syncing","params":[],"id":1}' localhost:8545
{
  "jsonrpc" : "2.0",
  "id" : 1,
  "result" : {
    "startingBlock" : "0xb0bc66",
    "currentBlock" : "0xb0bc66",
    "highestBlock" : "0xf29363"
  }
```

It's still syncing block: 11582566 (Jan 03, 2021). Continuously getting the below message in Besu tab, 

```shell
No sync target, waiting for peers. Current peers: 0
```

I am very new to running nodes. I'll look into the Besu sync issues , fix them and run chaind again (post complete sync.). Thanks a lot for your patience and support.

**Comment by sivathanuk** [comment]
Sure, noted. Thanks a lot.
