### ISSUE TITLE
Picking up from period 293 and t_validator_epoch_summaries remains empty

### ISSUE THREAD

**Issue by tuckerchapin** [wealdtech/chaind#72]
Running chaind for the first time seems to pick up at period 293 for some reason despite being given no start block. Shouldn't it start catching up from 0?

Also, maybe this is unrelated, but `select count(*) from t_validator_epoch_summaries` shows it to be empty so far. Does chaind have to be fully caught up before this will be filled out, or is there some config that's missing?

Running chaind with: 
```
--chaindb.url=<...> \
    --eth2client.address=<...> \
    --eth1client.address=<...>\
    --eth2client.timeout=15m \
    --blocks.enable=true \
    --finalizer.enable=true \
    --summarizer.enable=true \
    --summarizer.epochs.enable=true \
    --summarizer.blocks.enable=true \
    --summarizer.validators.enable=true \
    --eth1deposits.enable=false \
    --validators.enable=true \
    --beacon-committees.enable=true \
    --proposer-duties.enable=true \
    --sync-committees.enable=true \
    --log-level=debug
```

Produces:
```
{"level":"info","version":"0.6.17","time":"2023-01-03T19:58:15Z","message":"Starting chaind"}
{"level":"debug","time":"2023-01-03T19:58:15Z","message":"No tracing endpoint supplied; tracing not enabled"}
{"level":"info","listen_address":"127.0.0.1:8080","time":"2023-01-03T19:58:15Z","message":"Started prometheus metrics service"}
{"level":"info","service":"synccommittees","impl":"standard","period":293,"time":"2023-01-03T19:58:16Z","message":"Catching up from period"}
```

Beacon node reports:
```
{"data":{"head_slot":"5496205","sync_distance":"0","is_syncing":false,"is_optimistic":false}}
```

And `select * from t_metadata` returns:
| f_key                     | f_value                                                      |
|---------------------------|--------------------------------------------------------------|
| schema                    | `{"version": 8}`                                         |
| synccommittees.standard   | `{"latest_period": 306}`                                 |
| blocks.standard           | `{"latest_slot": 4232}`                                  |
| validators.standard       | `{"latest_epoch": 171749, "latest_balances_epoch": 0}` |
| proposerduties.standard   | `{"latest_epoch": 1121}`                                 |
| beaconcommittees.standard | `{"latest_epoch": 1121}`                                 |

**Comment by mcdee** [comment]
Sync committees didn't start until the Altair hard fork, so there won't be any data before that.

Summaries will only start to populate when the blocks are fully synced and finalized.

**Comment by tuckerchapin** [comment]
Thank you!
