### ISSUE TITLE
Some issues when indexing withdrawal-devnet-4

### ISSUE THREAD

**Issue by samlaf** [wealdtech/chaind#78]
Hey @mcdee,

first of all thanks a ton for building this.
We absolutely need to get this working properly to finish some of our needed infra for shapella.
We started indexing the withdrawal-devnet-4 (zhejiang still doesn't have partial withdrawals) to test withdrawals indexing. We ran into a few issues which probably have easy fixes, and which we'd like to get your feedback on. First two for now:

1. fork_schedule table runs into this error
```
{"level":"fatal","service":"spec","impl":"standard","error":"failed to set fork schedule: ERROR: duplicate key value violates unique constraint \"t_fork_schedule_f_epoch_key\" (SQLSTATE 23505)","time":"2023-02-07T01:06:23Z","message":"Failed to update fork schedule"}
```
That table uses the epoch as the main key, but the withdrawal-devnet-4 has altair and bellatrix forks [both at epoch 0](https://github.com/ethpandaops/withdrawals-testnet/blob/9aa91ba7465071b04b3225a99fcdeeccc860124d/withdrawal-devnet-4/custom_config_data/config.yaml#L24). We're just commenting this part of the code out since we don't need this table, but perhaps you want to fix this? Also is there any chance removing this table like we're doing might break some of the rest of the indexing or downstream applications?

2. sync committe errors
```
{"level":"warn","service":"blocks","impl":"standard","error":"no rows in result set","slot":0,"sync_committee_period":0,"time":"2023-02-07T01:07:03Z","message":"Failed to obtain sync committee period"}
{"level":"error","service":"blocks","impl":"standard","slot":0,"error":"failed to update block: failed to update sync aggregate: failed to obtain database sync aggregate: failed to obtain sync committee: no rows in result set","time":"2023-02-07T01:07:03Z","message":"Failed to catchup"}
```

This one seems worse, and not sure what's going on. Is this because the withdrawal-devnet-4 does something different? Or do I need to connect a validator client..? These two errors keep repeating and the indexing doesn't seem to move past slot 0. Any idea what's going on?

**Comment by mcdee** [comment]
Work is ongoing to support the testnets, as they often have slightly odd configurations.  A release should be forthcoming in the next couple of days to address these and other issues.

**Comment by samlaf** [comment]
I see! Is there anything we can do to help?
Otherwise, is there any other way you can think of for us to test withdrawals indexing as soon as possible?

**Comment by mcdee** [comment]
You should be able to build from master now to test this.  Note that you will need to recreate the database if you are working against devnet 4 or zhejiang.

**Comment by samlaf** [comment]
Getting this error from slot 43200 on zhejiang. Any idea what this means?
```
{"level":"info","version":"0.7.0-rc1","time":"2023-02-07T23:48:19+01:00","message":"Starting chaind"}
{"level":"info","service":"synccommittees","impl":"standard","period":-1,"time":"2023-02-07T23:48:19+01:00","message":"Catching up from period"}
{"level":"info","service":"synccommittees","impl":"standard","time":"2023-02-07T23:48:19+01:00","message":"Caught up"}
{"level":"info","service":"blocks","impl":"standard","slot":18446744073709551615,"time":"2023-02-07T23:48:19+01:00","message":"Catching up from slot"}
{"level":"info","service":"validators","impl":"standard","epoch":0,"time":"2023-02-07T23:48:19+01:00","message":"Catching up from epoch"}
{"level":"info","time":"2023-02-07T23:48:19+01:00","message":"All services operational"}
{"level":"info","service":"beaconcommittees","impl":"standard","epoch":0,"time":"2023-02-07T23:48:19+01:00","message":"Catching up from epoch"}
{"level":"info","service":"proposerduties","impl":"standard","epoch":18446744073709551615,"time":"2023-02-07T23:48:19+01:00","message":"Catching up from epoch"}
{"level":"info","service":"validators","impl":"standard","epoch":1423,"time":"2023-02-07T23:48:29+01:00","message":"Caught up"}
{"level":"info","service":"proposerduties","impl":"standard","time":"2023-02-07T23:51:00+01:00","message":"Caught up"}
{"level":"error","service":"blocks","impl":"standard","slot":43200,"error":"failed to update block: failed to obtain beacon block for slot: failed to request signed beacon block: GET failed with status 500: {\"code\":500,\"message\":\"UNHANDLED_ERROR: ExecutionLayerErrorPayloadReconstruction(0x1c5f2c9cbaa2e7c7abdb6fa73e7562beea21ce6af8a0e52a5634f6283db07418, EngineError(Api { error: Json(Error(\\\"invalid type: null, expected a sequence\\\", line: 0, column: 0)) }))\",\"stacktraces\":[]}","time":"2023-02-07T23:56:26+01:00","message":"Failed to catchup"}
{"level":"info","service":"blocks","impl":"standard","time":"2023-02-07T23:56:26+01:00","message":"Caught up"}
{"level":"error","service":"blocks","impl":"standard","slot":43200,"error":"failed to update block: failed to obtain beacon block for slot: failed to request signed beacon block: GET failed with status 500: {\"code\":500,\"message\":\"UNHANDLED_ERROR: ExecutionLayerErrorPayloadReconstruction(0x1c5f2c9cbaa2e7c7abdb6fa73e7562beea21ce6af8a0e52a5634f6283db07418, EngineError(Api { error: Json(Error(\\\"invalid type: null, expected a sequence\\\", line: 0, column: 0)) }))\",\"stacktraces\":[]}","time":"2023-02-07T23:56:36+01:00","message":"Failed to catchup"}
{"level":"error","service":"blocks","impl":"standard","slot":43200,"error":"failed to update block: failed to obtain beacon block for slot: failed to request signed beacon block: GET failed with status 500: {\"code\":500,\"message\":\"UNHANDLED_ERROR: ExecutionLayerErrorPayloadReconstruction(0x1c5f2c9cbaa2e7c7abdb6fa73e7562beea21ce6af8a0e52a5634f6283db07418, EngineError(Api { error: Json(Error(\\\"invalid type: null, expected a sequence\\\", line: 0, column: 0)) }))\",\"stacktraces\":[]}","time":"2023-02-07T23:56:48+01:00","message":"Failed to catchup"}
{"level":"error","service":"blocks","impl":"standard","slot":43200,"error":"failed to update block: failed to obtain beacon block for slot: failed to request signed beacon block: GET failed with status 500: {\"code\":500,\"message\":\"UNHANDLED_ERROR: ExecutionLayerErrorPayloadReconstruction(0x1c5f2c9cbaa2e7c7abdb6fa73e7562beea21ce6af8a0e52a5634f6283db07418, EngineError(Api { error: Json(Error(\\\"invalid type: null, expected a sequence\\\", line: 0, column: 0)) }))\",\"stacktraces\":[]}","time":"2023-02-07T23:57:00+01:00","message":"Failed to catchup"}
{"level":"error","service":"blocks","impl":"standard","slot":43200,"error":"failed to update block: failed to obtain beacon block for slot: failed to request signed beacon block: GET failed with status 500: {\"code\":500,\"message\":\"UNHANDLED_ERROR: ExecutionLayerErrorPayloadReconstruction(0x1c5f2c9cbaa2e7c7abdb6fa73e7562beea21ce6af8a0e52a5634f6283db07418, EngineError(Api { error: Json(Error(\\\"invalid type: null, expected a sequence\\\", line: 0, column: 0)) }))\",\"stacktraces\":[]}","time":"2023-02-07T23:57:12+01:00","message":"Failed to catchup"}
```

**Comment by samlaf** [comment]
EDIT 2: seems like a bug in geth..?
Seeing
```
########## BAD BLOCK #########
Block: 42314 (0x1c5f2c9cbaa2e7c7abdb6fa73e7562beea21ce6af8a0e52a5634f6283db07418)
Error: missing withdrawals in block body
Platform: geth (devel) go1.19.5 amd64 linux
VCS: 2f73f4f0-20230207
Chain config: &params.ChainConfig{ChainID:1337803, HomesteadBlock:0, DAOForkBlock:<nil>, DAOForkSupport:false, EIP150Block:0, EIP150Hash:0x0000000000000000000000000000000000000000000000000000000000000000, EIP155Block:0, EIP158Block:0, ByzantiumBlock:0, ConstantinopleBlock:0, PetersburgBlock:0, IstanbulBlock:0, MuirGlacierBlock:<nil>, BerlinBlock:0, LondonBlock:0, ArrowGlacierBlock:<nil>, GrayGlacierBlock:<nil>, MergeNetsplitBlock:<nil>, ShanghaiTime:(*uint64)(0xc0002d9920), CancunTime:(*uint64)(nil), PragueTime:(*uint64)(nil), TerminalTotalDifficulty:0, TerminalTotalDifficultyPassed:false, Ethash:(*params.EthashConfig)(nil), Clique:(*params.CliqueConfig)(nil)}
Receipts: 
##############################
```
in the logs, which seems to be expecting withdrawals in block 42314... whereas the fork block is 43200.

Anyways definitely not related to chaind. Sorry for bothering.

**Comment by mcdee** [comment]
Did you fix your geth issue and have chaind running?  I'm looking to release in the next day or two so if you have seen any issues it would be great to hear about them sooner rather than later.

**Comment by samlaf** [comment]
I fixed it by running nethermind instead :) chaind is working perfectly now!

One thing though, we need to retrieve all the validators with a given EL address as their withdrawal credential, and there doesn't seem to be a good way to do this right now. The `[t_block_bls_to_execution_changes](https://github.com/wealdtech/chaind/blob/353a130b5a0bd5eb18d99702bec247cf28795bac/services/chaindb/postgresql/upgrader.go#L1135)` table only has `f_block_root, f_block_number, f_index, f_from_bls_pubkey, f_to_execution_address` as fields. And there doesn't seem to be a way (?) to get back the the validator index or val_pubkey from his withdrawal pubkey (`f_from_bls_pubkey`). 

If this is right, could we add the val_pubkey to this table? Or anything else you think would be easier/cleaner. I can write the PR if needed.

**Comment by mcdee** [comment]
The operation carries the validator index, so adding a `f_validator_index` to `t_block_bls_to_execution_changes` would be simplest.  You would also need to add `f_withdrawal_credentials` to `t_validators`.  Between these two changes you could patch together the history of a validator's withdrawal credentials.

If you want to put together a PR with these changes please do, however as mentioned I'd like to get a release out soon so if this will take you a while let me know and I can release now and we can bring this functionality out in the next point release.

**Comment by samlaf** [comment]
Awesome, thanks for confirming. You can go ahead and release, we're building from source for now anyways. We can be in the next release. Is it correct to assume the next release will happen before shapella?
