### ISSUE TITLE
blocks do not progress with Teku, gives error "Slot x is not a phase0 slot"

### ISSUE THREAD

**Issue by mentheosis** [wealdtech/chaind#83]
I've been trying to get chaind to sync the last few months worth of data - I managed to work around https://github.com/wealdtech/chaind/issues/81 by editing metadata as suggested in that thread, but now I am seeing this in the logs:

`{"level":"error","service":"blocks","impl":"standard","slot":5477650,"error":"failed to update block: failed to obtain beacon block for slot: failed to request signed beacon block: GET failed with status 400: {\"code\":400,\"message\":\"Slot 5477650 is not a phase0 slot, please fetch via /eth/v2/beacon/blocks\"}","time":"2023-02-18T01:02:01Z","message":"Failed to catchup"}`

And my database is not progressing in blocks or summaries at all now. Seems like a problem with the eth2client lib perhaps hitting the wrong endpoint against teku, but wondering if there some config change that I am missing?

**Comment by mcdee** [comment]
Is the teku node a fully synced beacon node?  What response do you receive if you attempt to get `/eth/v2/beacon/blocks/0` from it?

**Comment by mentheosis** [comment]
Yes it is, here are some example responses if I hit directly:

/eth/v2/beacon/blocks/0
`{
  "version": "phase0",
  "execution_optimistic": false,
  "data": {
    "message": {
      "slot": "0",
      "proposer_index": "0",
      "parent_root": "0x0000000000000000000000000000000000000000000000000000000000000000",
      "state_root": "0x7e76880eb67bbdc86250aa578958e9d0675e64e714337855204fb5abaaf82c2b",
      "body": {
        "randao_reveal": "0x000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
        "eth1_data": {
          "deposit_root": "0x0000000000000000000000000000000000000000000000000000000000000000",
          "deposit_count": "0",
          "block_hash": "0x0000000000000000000000000000000000000000000000000000000000000000"
        },
        "graffiti": "0x0000000000000000000000000000000000000000000000000000000000000000",
        "proposer_slashings": [],
        "attester_slashings": [],
        "attestations": [],
        "deposits": [],
        "voluntary_exits": []
      }
    },
    "signature": "0x000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
  }
}`

/eth/v2/beacon/blocks/5477650
`{
  "version": "bellatrix",
  "execution_optimistic": false,
  "data": {
    "message": {
      "slot": "5477650",
      "proposer_index": "18133",
      "parent_root": "0x4dd2caa16c831e12f926de43f59dbd19b5b43229cb9a4af589cc6660a9f243f5",
      "state_root": "0x9d2057062bdec330ebeb292a29a5ede63df9dbfe661c0eac38a075bf6dbe9a83",
      "body": {
        "randao_reveal": "0xad2a81f1bad6e877d6c027434324e1f9253f9ba56613aa40111bbce3420933092ce79c950634dcebee498b5475c3777910648b5991c04f8fa8402e5b33306064ee266109a6ae804dd1193e8553174fbd2017d9280fcbee73858f6b7289ff66cd",
        "eth1_data": {
          "deposit_root": "0x099d7e37a7b5fdba0aaf1c2b7fc980210d4df7f653926230c431c8b3c3e2ef8b",
          "deposit_count": "506285",
          "block_hash": "0x3f8b6f3d0127e3733400bf32c97dc0636de81d7be7a34b692ea2fde808ae46f2"
        },
        "graffiti": "0x0000000000000000000000000000000000000000000000000000000000000000",
        "proposer_slashings": [],
        "attester_slashings": [],
        "attestations": [...`

**Comment by mcdee** [comment]
It may be that `chaind` was started at a point where it didn't have access to the beacon node properly so decided that it didn't support the `v2` endpoints.  If you restart `chaind` it should be able to progress.

**Comment by mentheosis** [comment]
Oh, yes, one more restart of chaind service and it seems to be progressing now on blocks, thanks. Would you expect t_validator_epoch_summaries to begin populating only after the blocks service has caught up, or in parallel?

thanks!

**Comment by mcdee** [comment]
Summaries only run after finalization, and finalization requires the block data so it will have to wait for the blocks to be populated.

**Comment by mentheosis** [comment]
restarting the service again caused it start finding the v2 endpoints as suggested, sovled
