### ISSUE TITLE
README upgrade-chaind section is vague and unclear

### ISSUE THREAD

**Issue by samlaf** [wealdtech/chaind#85]
The [upgrading-chaind](https://github.com/wealdtech/chaind#upgrading-chaind) section is super unclear.

> chaind should upgrade automatically from earlier versions. Note that the upgrade process can take a long time to complete, especially where data needs to be refetched or recalculated. chaind should be left to complete the upgrade, to avoid the situation where additional fields are not fully populated. If this does occur then chaind can be run with the options --blocks.start-slot=0 --blocks.refetch=true to force chaind to refetch all blocks.

What is meant by "if THIS does occur"? Additional fields not being fully populated? When can this happen? Only if a user runs chaind and stops it somehow in the middle of the upgrade process? Or are there certain breaking updates that forcefully require rerunning chaind with the start-slot=0 and refetch=true parameters set? Are these updates then mentioned in the release? What happens if we don't run chaind with those parameters by mistake?

**Comment by mcdee** [comment]
"this" does indeed refer to additional fields not being fully populated.  It occurs if `chaind` fails to complete the update, because a user kills the process or the server reboots or similar.

If an update requires refetching slots it is handled automatically.

**Comment by samlaf** [comment]
Updated the docs and PR was merged. closing.
