### ISSUE TITLE
Multiple chaind clients pointing to the same db

### ISSUE THREAD

**Issue by mpjunior92** [wealdtech/chaind#86]
Hello,

I am Matheus from LayrLabs and first I would like to thank you for making this tool open source, thanks. We are planning to run multiple chaind clients pointing to the same database to have high availability in our services: should one chaind client fail for whatever reason, we have another one running and indexing CL data. Do you see any possible problem that could arise in doing so? I went through all `INSERT INTO` queries and all of them use upserts, thus I think it'd be OK, aside from the fact that a lot of upserts are going to happen every single second. The reason we are consideing this approach is that we can easily scale up / down chaind instances while having a single db instead of one per each chaind client. Any suggestions / thoughts on this are welcome.

Thank you.

**Comment by mcdee** [comment]
I'm pretty sure this will fail horribly, as metadata will be overwritten by the two instances.  If you want a highly available system then I recommend two separate instances, each with their own database, and some sort of load balancer/failover system in front of it e.g. https://severalnines.com/resources/whitepapers/postgresql-load-balancing-haproxy

**Comment by mpjunior92** [comment]
I see, so I think that also holds true for the CL connection as well: each chaind should have its own CL client as each has its own local db, right?

**Comment by mcdee** [comment]
Multiple `chaind` instances could read from the same beacon node, but that would give you a single point of failure if it was corrupted or unavailable.

**Comment by mpjunior92** [comment]
Sure, yeah, we are going to use a highly available deployment for the beacon nodes to avoid SPOF. Thank you very much for your help.

**Comment by mpjunior92** [comment]
Any thoughts on this?
