### ISSUE TITLE
Chaind failed to update block at slot 2

### ISSUE THREAD

**Issue by AmbitionCX** [wealdtech/chaind#96]
Hi there! I am facing an issue where the chaind is unable to fetch the block at slot 2. It appears that the error is caused by the failure to fetch beacon committees.
```
{"level":"error","service":"blocks","impl":"standard","slot":2,"error":"failed to update block: failed to update attestations: failed to obtain database attestation: failed to fetch beacon committees: GET failed with status 404: {\"code\":404,\"message\":\"Not found\"}","time":"2023-12-12T19:31:13+08:00","message":"Failed to catchup"}
```
I have tried to set the `--beacon-committees.enable=false` or set the `beacon-committees: enable: false` in `chaind.yml` file. But both settings do not work. I still get the same error as the following:
```
{"level":"error","service":"blocks","impl":"standard","slot":2,"error":"failed to update block: failed to update attestations: failed to obtain database attestation: failed to fetch beacon committees: GET failed with status 404: {\"code\":404,\"message\":\"Not found\"}","time":"2023-12-12T21:00:49+08:00","message":"Failed to catchup"}
```

I'm using teku + geth clients. I try to get the slot 2 from teku:
```
curl http://localhost:5051/eth/v1/beacon/blocks/2/root
```
and I get the following results, which has the same root with block 2 in the [beaconcha.in](https://beaconcha.in/slot/2):
```json
{
"data":{
"root":"0x2757f6fd8590925cd000a86a3e543f98a93eae23781783a33e34504729a8ad0c"
},
"execution_optimistic":false,
"finalized":true
}
```

**Comment by mcdee** [comment]
Is your teku node an archive node?  What does the following return?

```
curl http://localhost:5051/eth/v1/beacon/states/2/committees
```

If your node is configured correctly as an archive node this will return data, if not then it will return a 404.

**Comment by AmbitionCX** [comment]
Thank you. My teku node is not configured as an archive node. I change the teku config file, and restart chaind, it runs correctly.
```
data-storage-mode: "archive"
```
