### ISSUE TITLE
DB error with type of f_epoch column

### ISSUE THREAD

**Issue by JeroniMan** [wealdtech/chaind#98]
Hello!
I tried to use your service and catch error with data type of f_epoch column. 
When chaind try insert value 18446744073709551615 in int8 postgres type happend overflow of data type.

> {"level":"trace","service":"chaintime","impl":"standard","epoch":18446744073709551615,"time":"2024-01-29T23:37:23Z","message":"Obtained Deneb fork epoch"}

Error:
> {"level":"fatal","service":"spec","impl":"standard","error":"failed to set fork schedule: failed to encode args[1]: unable to encode 0xffffffffffffffff into binary format for int8 (OID 20): 18446744073709551615 is greater than maximum value for int64","time":"2024-01-29T23:37:23Z","message":"Failed to update fork schedule"}

I check it with next config:
- chaind 0.8.1
- go1.20.13 linux/amd64
- postgres 12 and 14
- also attach my config and [log](https://github.com/wealdtech/chaind/files/14095989/log_chaind.log).

I can solve this problem when change type: BIGINT -> NUMERIC.

![image_2024-01-30_02-41-07 (2)](https://github.com/wealdtech/chaind/assets/31256186/80b954c2-5606-461b-8d9b-0523d83ee502)

**Comment by mcdee** [comment]
The error is due to `chaind` erroneously including fork schedule entries that it should not.  I will look to release 0.8.2 with this fix soon.
